# Generated by Django 5.1.6 on 2025-06-21 22:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_code', models.TextField()),
                ('programming_language', models.CharField(default='python', max_length=20)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('partial', 'Partial')], max_length=10)),
                ('score', models.IntegerField(help_text='Score/Grade out of 100')),
                ('overall_feedback', models.TextField(blank=True)),
                ('correctness_feedback', models.TextField(blank=True)),
                ('code_quality_feedback', models.TextField(blank=True)),
                ('improvements', models.JSONField(blank=True, default=list)),
                ('positive_points', models.JSONField(blank=True, default=list)),
                ('test_results', models.JSONField(blank=True, default=list)),
                ('next_steps', models.JSONField(blank=True, default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_best', models.BooleanField(default=False)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('user', 'challenge', 'is_best')},
            },
        ),
    ]
