# Generated by Django 5.1.6 on 2025-06-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_submission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together=set(),
        ),
    ]
